# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameModel(
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameModel(
            old_name='tests',
            new_name='test',
        ),
    ]
